[project]
name = "comet-patent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "accelerate>=1.0.1",
    "datasets>=3.1.0",
    "matplotlib>=3.7.5",
    "pandas>=2.0.3",
    "scikit-learn>=1.3.2",
    "tensorboard>=2.14.0",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
    "transformers>=4.46.3",
    "wandb>=0.19.6",
]
